[package]
name = "trusty-cryptoprov-aws-kms"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["crypto", "aws", "kms"]
description = "AWS KMS signing provider for trusty-cryptoprov"

[dependencies]
trusty-cryptoprov-core.workspace = true
aws-config = "1"
aws-sdk-kms = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
pem = "4.0.0"
tracing = "0.1"
