[package]
name = "hsm-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "CLI to work with keys backed by HSM or KMS (AWS KMS, GCP KMS, PKCS#11)"

[[bin]]
name = "hsm-tool"
path = "src/main.rs"

[dependencies]
trusty-cryptoprov-core.workspace = true
trusty-cryptoprov-inmem.workspace = true
trusty-cryptoprov-pkcs11.workspace = true
trusty-cryptoprov-aws-kms.workspace = true
trusty-cryptoprov-gcp-kms.workspace = true
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
time = { version = "0.3", features = ["formatting"] }
uuid = { version = "1", features = ["v4"] }
