[package]
name = "trusty-cryptoprov-pkcs11"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords = ["crypto", "pkcs11", "hsm"]
description = "PKCS#11 signing provider for trusty-cryptoprov"

[dependencies]
trusty-cryptoprov-core.workspace = true
trusty-crypto11.workspace = true
secrecy = { version = "0.10", features = ["serde"] }
url = "2"
